### PR TITLE
Wrap dat urls in anchor tags

### PR DESCRIPTION
**Pull request by maxhallinan**
This makes it easier to navigate to a Rotonde instance from the list. Of course, this only works in Beaker Browser but it seems like Beaker Browser would be the primary client for this page.

### CODE REVIEW

**Comment by neauoire** [comment]
Can @cblgh confirm that this won't break anything? Can this be done programatically instead?

**Comment by cblgh** [comment]
@neauoire yeah i think we can move to a programmatic approach now. i was going to do it initially, but chose the simpler route as i didn't know if it would take off.

**Comment by maxhallinan** [comment]
@neauoire @cblgh do you mean moving the list to a json array of `{ "name": "", "target": "dat://" }` pairs and rendering those on the client, or dynamically wrapping the text content of the `div` in anchor tags?

**Comment by cblgh** [comment]
@maxhallinan  sorry for the delayed response! this is what i had in mind :) https://github.com/Rotonde/People/commit/c6a87db2f8152dc3d5f9545efc2a65dab6da201a

**Comment by maxhallinan** [comment]
👍🏻

**Pull request closed without merging**
