### PR TITLE
Additions for 2017-10-19

### PR DESCRIPTION
**Pull request by composition4**
Maybe these can be added in increment commits for each user and then merged at EOD? 😸 💜

### CODE REVIEW

**Comment by composition4** [comment]
ChangbaiLi wanted to keep the IG account instead of twitter for compartmentalization purposes

**Comment by cblgh** [comment]
lmk when ur EOD is m8y

**Comment by composition4** [comment]
oki ~14 hrs mark naoish

**Comment by cblgh** [comment]
thx bb:3

**Comment by composition4** [comment]
💜

**Comment by composition4** [comment]
serapath should be `nodupe` with this commit (overlapped, but merged in)

**Pull request merged**
